openapi: 3.1.0

info:
  title: Checkin API
  version: 0.1.0
  description: Checkin API

paths:
  /customer:
    get:
      summary: Customer を取得
      tags:
        - Customer
      operationId: getCustomer
      parameters:
        - $ref: '#/components/parameters/CustomerId'
        - name: traq_id
          description: traQ ID
          in: query
          schema:
            type: string
        - name: email
          description: Email
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Customer を作成
      tags:
        - Customer
      operationId: postCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCustomerRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          $ref: '#/components/responses/InternalServerError'
    patch:
      summary: Customer を更新
      tags:
        - Customer
      operationId: patchCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCustomerRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /invoice:
    post:
      summary: Invoice を作成
      tags:
        - Invoice
      operationId: postInvoice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInvoiceRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /webhook/invoice-paid:
    post:
      summary: Webhook の invoice.paid イベントを受け取る
      tags:
        - Webhook
      operationId: postWebhookInvoicePaid
      parameters:
        - name: Stripe-Signature
          description: Stripe が送信する認証情報
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
      responses:
        '204':
          description: No content
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /list/invoices:
    get:
      summary: 請求書由来の入金一覧を取得
      tags:
        - List
      operationId: getInvoices
      parameters:
        - $ref: '#/components/parameters/CustomerId'
        - $ref: '#/components/parameters/SubscriptionId'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/StartingAfter'
        - $ref: '#/components/parameters/EndingBefore'
        - name: status
          description: 請求書ステータス
          in: query
          schema:
            type: string
            enum:
              - draft
              - open
              - paid
              - uncollectible
              - void
        - name: collection_method
          description: 請求書の支払い方法
          in: query
          schema:
            type: string
            enum:
              - charge_automatically
              - send_invoice
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invoice'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /list/checkout-sessions:
    get:
      summary: オンライン決済ページ由来の入金一覧を取得
      tags:
        - List
      operationId: getCheckoutSessions
      parameters:
        - $ref: '#/components/parameters/CustomerId'
        - $ref: '#/components/parameters/SubscriptionId'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/StartingAfter'
        - $ref: '#/components/parameters/EndingBefore'
        - name: payment_intent_id
          description: PaymentIntent ID
          in: query
          schema:
            type: string
        - name: status
          description: Checkout Session のステータス
          in: query
          schema:
            type: string
            enum:
              - complete
              - expired
              - open
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCheckoutSessionsResponse'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  parameters:
    CustomerId:
      name: customer_id
      in: query
      description: Customer ID
      schema:
        type: string
        example: cus_NeZwdNtLEOXuvB
    SubscriptionId:
      name: subscription_id
      in: query
      description: Subscription ID
      schema:
        type: string
        example: sub_NeZwdNtLEOXuvB
    Limit:
      name: limit
      in: query
      description: 取得件数
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
    StartingAfter:
      name: starting_after
      in: query
      description: 指定された ID のオブジェクト以降のオブジェクトを取得
      schema:
        type: string
    EndingBefore:
      name: ending_before
      in: query
      description: 指定された ID のオブジェクト以前のオブジェクトを取得
      schema:
        type: string
  responses:
    Forbidden:
      description: Forbidden
    NotFound:
      description: Not found
    InternalServerError:
      description: Internal server error
  schemas:
    Customer:
      description: Customer の情報
      type: object
      properties:
        id:
          type: string
          description: Customer ID
          example: cus_NeZwdNtLEOXuvB
        traq_id:
          type: string
          description: traQ ID
          example: traP
        email:
          type: string
          description: Email
          example: jennyrosen@example.com
        name:
          type: string
          description: Name
          example: Jenny Rosen
    PostCustomerRequest:
      description: Customer 作成リクエスト
      type: object
      properties:
        email:
          type: string
          description: Email
        name:
          type: string
          description: Name
        traq_id:
          type: string
          description: traQ ID
      required:
        - email
        - name
    PostInvoiceRequest:
      description: Invoice 作成リクエスト
      type: object
      properties:
        customer_id:
          type: string
          description: Customer ID
        product_id:
          type: string
          description: Product ID
      required:
        - customer_id
        - product_id
    Invoice:
      description: Invoice の情報
      type: object
      properties:
        has_more:
          type: boolean
          description: 次のページがあるか
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Invoice ID
                example: in_1MtHbELkdIwHu7ixl4OzzPMv
              amount_due:
                type: integer
                description: 最終的に支払う金額
                example: 0
              amount_paid:
                type: integer
                description: 支払い済み金額
                example: 0
              amount_remaining:
                type: integer
                description: 支払い残高
                example: 0
              created:
                type: integer
                description: 作成日時 (Unix 時間)
                example: 1680644467
              customer:
                $ref: '#/components/schemas/Customer'
              status:
                type: string
                description: 請求書ステータス
                enum:
                  - draft
                  - open
                  - paid
                  - uncollectible
                  - void
                example: draft
              payment_intent:
                type:
                  - string
                description: この請求書に関連付けられた PaymentIntent
                example: null
              product_id:
                type: string
                description: Product ID
                example: prod_NWjs8kKbJWmuuc
    GetCheckoutSessionsResponse:
      description: オンライン決済ページ由来の入金一覧
      type: object
      properties:
        has_more:
          type: boolean
          description: 次のページがあるか
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: Checkout Session ID
                example: cs_test_1234567890
              amount_total:
                type: integer
                description: 支払い金額
                example: 2198
              amount_subtotal:
                type: integer
                description: 割引・税金を含まない支払い金額
                example: 1998
              created:
                type: integer
                description: 作成日時 (Unix 時間)
                example: 1679600215
              customer:
                $ref: '#/components/schemas/Customer'
              status:
                type: string
                description: Checkout Session のステータス
                enum:
                  - complete
                  - expired
                  - open
                example: open
              payment_intent:
                type:
                  - string
                description: この Checkout Session に関連付けられた PaymentIntent
                example: null
              product_id:
                type: string
                description: Product ID
                example: prod_NWjs8kKbJWmuuc

tags:
  - name: Customer
    description: Customer API
  - name: Invoice
    description: Invoice API
  - name: Webhook
    description: Webhook API
  - name: List
    description: List API
