// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GetCheckoutSessionsResponseDataStatus.
const (
	GetCheckoutSessionsResponseDataStatusComplete GetCheckoutSessionsResponseDataStatus = "complete"
	GetCheckoutSessionsResponseDataStatusExpired  GetCheckoutSessionsResponseDataStatus = "expired"
	GetCheckoutSessionsResponseDataStatusOpen     GetCheckoutSessionsResponseDataStatus = "open"
)

// Defines values for InvoiceDataStatus.
const (
	InvoiceDataStatusDraft         InvoiceDataStatus = "draft"
	InvoiceDataStatusOpen          InvoiceDataStatus = "open"
	InvoiceDataStatusPaid          InvoiceDataStatus = "paid"
	InvoiceDataStatusUncollectible InvoiceDataStatus = "uncollectible"
	InvoiceDataStatusVoid          InvoiceDataStatus = "void"
)

// Defines values for GetCheckoutSessionsParamsStatus.
const (
	GetCheckoutSessionsParamsStatusComplete GetCheckoutSessionsParamsStatus = "complete"
	GetCheckoutSessionsParamsStatusExpired  GetCheckoutSessionsParamsStatus = "expired"
	GetCheckoutSessionsParamsStatusOpen     GetCheckoutSessionsParamsStatus = "open"
)

// Defines values for GetInvoicesParamsStatus.
const (
	GetInvoicesParamsStatusDraft         GetInvoicesParamsStatus = "draft"
	GetInvoicesParamsStatusOpen          GetInvoicesParamsStatus = "open"
	GetInvoicesParamsStatusPaid          GetInvoicesParamsStatus = "paid"
	GetInvoicesParamsStatusUncollectible GetInvoicesParamsStatus = "uncollectible"
	GetInvoicesParamsStatusVoid          GetInvoicesParamsStatus = "void"
)

// Defines values for GetInvoicesParamsCollectionMethod.
const (
	ChargeAutomatically GetInvoicesParamsCollectionMethod = "charge_automatically"
	SendInvoice         GetInvoicesParamsCollectionMethod = "send_invoice"
)

// Admin 管理者の情報
type Admin struct {
	// Id traQ ID
	Id string `json:"id"`
}

// Customer Customer の情報
type Customer struct {
	// Email Email
	Email *string `json:"email,omitempty"`

	// Id Customer ID
	Id *string `json:"id,omitempty"`

	// Name Name
	Name *string `json:"name,omitempty"`

	// TraqId traQ ID
	TraqId *string `json:"traq_id,omitempty"`
}

// GetCheckoutSessionsResponse オンライン決済ページ由来の入金一覧
type GetCheckoutSessionsResponse struct {
	Data *[]struct {
		// AmountSubtotal 割引・税金を含まない支払い金額
		AmountSubtotal *int64 `json:"amount_subtotal,omitempty"`

		// AmountTotal 支払い金額
		AmountTotal *int64 `json:"amount_total,omitempty"`

		// Created 作成日時 (Unix 時間)
		Created *int64 `json:"created,omitempty"`

		// Customer Customer の情報
		Customer *Customer `json:"customer,omitempty"`

		// Id Checkout Session ID
		Id *string `json:"id,omitempty"`

		// PaymentIntent この Checkout Session に関連付けられた PaymentIntent
		PaymentIntent *string `json:"payment_intent,omitempty"`

		// ProductId Product ID
		ProductId *string `json:"product_id,omitempty"`

		// Status Checkout Session のステータス
		Status *GetCheckoutSessionsResponseDataStatus `json:"status,omitempty"`
	} `json:"data,omitempty"`

	// HasMore 次のページがあるか
	HasMore *bool `json:"has_more,omitempty"`
}

// GetCheckoutSessionsResponseDataStatus Checkout Session のステータス
type GetCheckoutSessionsResponseDataStatus string

// Invoice Invoice の情報
type Invoice struct {
	Data *[]struct {
		// AmountDue 最終的に支払う金額
		AmountDue *int64 `json:"amount_due,omitempty"`

		// AmountPaid 支払い済み金額
		AmountPaid *int64 `json:"amount_paid,omitempty"`

		// AmountRemaining 支払い残高
		AmountRemaining *int64 `json:"amount_remaining,omitempty"`

		// Created 作成日時 (Unix 時間)
		Created *int64 `json:"created,omitempty"`

		// Customer Customer の情報
		Customer *Customer `json:"customer,omitempty"`

		// Id Invoice ID
		Id *string `json:"id,omitempty"`

		// PaymentIntent この請求書に関連付けられた PaymentIntent
		PaymentIntent *string `json:"payment_intent,omitempty"`

		// ProductId Product ID
		ProductId *string `json:"product_id,omitempty"`

		// Status 請求書ステータス
		Status *InvoiceDataStatus `json:"status,omitempty"`
	} `json:"data,omitempty"`

	// HasMore 次のページがあるか
	HasMore *bool `json:"has_more,omitempty"`
}

// InvoiceDataStatus 請求書ステータス
type InvoiceDataStatus string

// PostCustomerRequest Customer 作成リクエスト
type PostCustomerRequest struct {
	// Email Email
	Email string `json:"email"`

	// Name Name
	Name string `json:"name"`

	// TraqId traQ ID
	TraqId *string `json:"traq_id,omitempty"`
}

// PostInvoiceRequest Invoice 作成リクエスト
type PostInvoiceRequest struct {
	// CustomerId Customer ID
	CustomerId string `json:"customer_id"`

	// ProductId Product ID
	ProductId string `json:"product_id"`
}

// PostInvoiceResponse Invoice creation result
type PostInvoiceResponse struct {
	// InvoiceId Invoice ID
	InvoiceId string `json:"invoice_id"`

	// PaymentUrl Hosted invoice payment URL
	PaymentUrl string `json:"payment_url"`
}

// PostVerifyEmailConfirmRequest Verify email confirm request
type PostVerifyEmailConfirmRequest struct {
	Token string `json:"token"`
}

// PostVerifyEmailRequest Verify email request
type PostVerifyEmailRequest struct {
	// Email isct email
	Email openapi_types.Email `json:"email"`
}

// PostVerifyEmailResponse Verify email start response
type PostVerifyEmailResponse struct {
	// Email normalized email
	Email string `json:"email"`

	// Redirect `//` で始まらないアプリ内の相対パス
	Redirect RelativeRedirectPath `json:"redirect"`
}

// RelativeRedirectPath `//` で始まらないアプリ内の相対パス
type RelativeRedirectPath = string

// StripeEvent Generic Stripe event payload
type StripeEvent map[string]interface{}

// CsrfToken defines model for CsrfToken.
type CsrfToken = string

// CustomerId defines model for CustomerId.
type CustomerId = string

// EndingBefore defines model for EndingBefore.
type EndingBefore = string

// Limit defines model for Limit.
type Limit = int

// StartingAfter defines model for StartingAfter.
type StartingAfter = string

// SubscriptionId defines model for SubscriptionId.
type SubscriptionId = string

// VerifyEmailRedirect `//` で始まらないアプリ内の相対パス
type VerifyEmailRedirect = RelativeRedirectPath

// GetCheckoutSessionsParams defines parameters for GetCheckoutSessions.
type GetCheckoutSessionsParams struct {
	// CustomerId Customer ID
	CustomerId *CustomerId `form:"customer_id,omitempty" json:"customer_id,omitempty"`

	// SubscriptionId Subscription ID
	SubscriptionId *SubscriptionId `form:"subscription_id,omitempty" json:"subscription_id,omitempty"`

	// Limit 取得件数
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter 指定された ID のオブジェクト以降のオブジェクトを取得
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore 指定された ID のオブジェクト以前のオブジェクトを取得
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`

	// PaymentIntentId PaymentIntent ID
	PaymentIntentId *string `form:"payment_intent_id,omitempty" json:"payment_intent_id,omitempty"`

	// Status Checkout Session のステータス
	Status *GetCheckoutSessionsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetCheckoutSessionsParamsStatus defines parameters for GetCheckoutSessions.
type GetCheckoutSessionsParamsStatus string

// GetCustomerParams defines parameters for GetCustomer.
type GetCustomerParams struct {
	// CustomerId Customer ID
	CustomerId *CustomerId `form:"customer_id,omitempty" json:"customer_id,omitempty"`

	// TraqId traQ ID
	TraqId *string `form:"traq_id,omitempty" json:"traq_id,omitempty"`

	// Email Email
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}

// PatchCustomerParams defines parameters for PatchCustomer.
type PatchCustomerParams struct {
	// XCSRFToken Double-submit CSRF token。`/csrf` または `POST /verify-email/confirm` が発行した `__Host-checkin_csrf` cookie の値をそのまま送る。
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PostCustomerParams defines parameters for PostCustomer.
type PostCustomerParams struct {
	// XCSRFToken Double-submit CSRF token。`/csrf` または `POST /verify-email/confirm` が発行した `__Host-checkin_csrf` cookie の値をそのまま送る。
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// GetInvoicesParams defines parameters for GetInvoices.
type GetInvoicesParams struct {
	// CustomerId Customer ID
	CustomerId *CustomerId `form:"customer_id,omitempty" json:"customer_id,omitempty"`

	// SubscriptionId Subscription ID
	SubscriptionId *SubscriptionId `form:"subscription_id,omitempty" json:"subscription_id,omitempty"`

	// Limit 取得件数
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter 指定された ID のオブジェクト以降のオブジェクトを取得
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore 指定された ID のオブジェクト以前のオブジェクトを取得
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`

	// Status 請求書ステータス
	Status *GetInvoicesParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// CollectionMethod 請求書の支払い方法
	CollectionMethod *GetInvoicesParamsCollectionMethod `form:"collection_method,omitempty" json:"collection_method,omitempty"`
}

// GetInvoicesParamsStatus defines parameters for GetInvoices.
type GetInvoicesParamsStatus string

// GetInvoicesParamsCollectionMethod defines parameters for GetInvoices.
type GetInvoicesParamsCollectionMethod string

// PostInvoiceParams defines parameters for PostInvoice.
type PostInvoiceParams struct {
	// XCSRFToken Double-submit CSRF token。`/csrf` または `POST /verify-email/confirm` が発行した `__Host-checkin_csrf` cookie の値をそのまま送る。
	XCSRFToken CsrfToken `json:"X-CSRF-Token"`
}

// PostVerifyEmailParams defines parameters for PostVerifyEmail.
type PostVerifyEmailParams struct {
	// Redirect 検証後に遷移する相対パス
	Redirect *VerifyEmailRedirect `form:"redirect,omitempty" json:"redirect,omitempty"`
}

// GetVerifyEmailConfirmParams defines parameters for GetVerifyEmailConfirm.
type GetVerifyEmailConfirmParams struct {
	// Token 確認メールに含まれるワンタイムトークン
	Token string `form:"token" json:"token"`
}

// PostWebhookInvoicePaidParams defines parameters for PostWebhookInvoicePaid.
type PostWebhookInvoicePaidParams struct {
	// StripeSignature Stripe が送信する認証情報
	StripeSignature string `json:"Stripe-Signature"`
}

// PatchCustomerJSONRequestBody defines body for PatchCustomer for application/json ContentType.
type PatchCustomerJSONRequestBody = PostCustomerRequest

// PostCustomerJSONRequestBody defines body for PostCustomer for application/json ContentType.
type PostCustomerJSONRequestBody = PostCustomerRequest

// PostInvoiceJSONRequestBody defines body for PostInvoice for application/json ContentType.
type PostInvoiceJSONRequestBody = PostInvoiceRequest

// PostVerifyEmailJSONRequestBody defines body for PostVerifyEmail for application/json ContentType.
type PostVerifyEmailJSONRequestBody = PostVerifyEmailRequest

// PostVerifyEmailConfirmFormdataRequestBody defines body for PostVerifyEmailConfirm for application/x-www-form-urlencoded ContentType.
type PostVerifyEmailConfirmFormdataRequestBody = PostVerifyEmailConfirmRequest

// PostWebhookInvoicePaidJSONRequestBody defines body for PostWebhookInvoicePaid for application/json ContentType.
type PostWebhookInvoicePaidJSONRequestBody = StripeEvent

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 管理者の一覧を取得
	// (GET /admin)
	GetAdmins(ctx echo.Context) error
	// オンライン決済ページ由来の入金一覧を取得
	// (GET /checkout/sessions)
	GetCheckoutSessions(ctx echo.Context, params GetCheckoutSessionsParams) error
	// CSRF トークン用 cookie を発行
	// (GET /csrf)
	GetCsrf(ctx echo.Context) error
	// Customer を取得
	// (GET /customers)
	GetCustomer(ctx echo.Context, params GetCustomerParams) error
	// Customer を更新
	// (PATCH /customers)
	PatchCustomer(ctx echo.Context, params PatchCustomerParams) error
	// Customer を作成
	// (POST /customers)
	PostCustomer(ctx echo.Context, params PostCustomerParams) error
	// 請求書由来の入金一覧を取得
	// (GET /invoices)
	GetInvoices(ctx echo.Context, params GetInvoicesParams) error
	// Invoice を作成
	// (POST /invoices)
	PostInvoice(ctx echo.Context, params PostInvoiceParams) error
	// isct メールアドレスの確認メールを送信
	// (POST /verify-email)
	PostVerifyEmail(ctx echo.Context, params PostVerifyEmailParams) error
	// メール確認トークンの確認ページを表示
	// (GET /verify-email/confirm)
	GetVerifyEmailConfirm(ctx echo.Context, params GetVerifyEmailConfirmParams) error
	// メール確認トークンを消費してログインを完了
	// (POST /verify-email/confirm)
	PostVerifyEmailConfirm(ctx echo.Context) error
	// Webhook の invoice.paid イベントを受け取る
	// (POST /webhook/invoice-paid)
	PostWebhookInvoicePaid(ctx echo.Context, params PostWebhookInvoicePaidParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAdmins converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdmins(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdmins(ctx)
	return err
}

// GetCheckoutSessions converts echo context to params.
func (w *ServerInterfaceWrapper) GetCheckoutSessions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCheckoutSessionsParams
	// ------------- Optional query parameter "customer_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "customer_id", ctx.QueryParams(), &params.CustomerId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter customer_id: %s", err))
	}

	// ------------- Optional query parameter "subscription_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "subscription_id", ctx.QueryParams(), &params.SubscriptionId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter subscription_id: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", ctx.QueryParams(), &params.StartingAfter)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter starting_after: %s", err))
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", ctx.QueryParams(), &params.EndingBefore)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ending_before: %s", err))
	}

	// ------------- Optional query parameter "payment_intent_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "payment_intent_id", ctx.QueryParams(), &params.PaymentIntentId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter payment_intent_id: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCheckoutSessions(ctx, params)
	return err
}

// GetCsrf converts echo context to params.
func (w *ServerInterfaceWrapper) GetCsrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCsrf(ctx)
	return err
}

// GetCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) GetCustomer(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomerParams
	// ------------- Optional query parameter "customer_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "customer_id", ctx.QueryParams(), &params.CustomerId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter customer_id: %s", err))
	}

	// ------------- Optional query parameter "traq_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "traq_id", ctx.QueryParams(), &params.TraqId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter traq_id: %s", err))
	}

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameter("form", true, false, "email", ctx.QueryParams(), &params.Email)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCustomer(ctx, params)
	return err
}

// PatchCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) PatchCustomer(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchCustomerParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CSRF-Token, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CSRF-Token: %s", err))
		}

		params.XCSRFToken = XCSRFToken
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-CSRF-Token is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchCustomer(ctx, params)
	return err
}

// PostCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) PostCustomer(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostCustomerParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CSRF-Token, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CSRF-Token: %s", err))
		}

		params.XCSRFToken = XCSRFToken
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-CSRF-Token is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCustomer(ctx, params)
	return err
}

// GetInvoices converts echo context to params.
func (w *ServerInterfaceWrapper) GetInvoices(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInvoicesParams
	// ------------- Optional query parameter "customer_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "customer_id", ctx.QueryParams(), &params.CustomerId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter customer_id: %s", err))
	}

	// ------------- Optional query parameter "subscription_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "subscription_id", ctx.QueryParams(), &params.SubscriptionId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter subscription_id: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", ctx.QueryParams(), &params.StartingAfter)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter starting_after: %s", err))
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", ctx.QueryParams(), &params.EndingBefore)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ending_before: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "collection_method" -------------

	err = runtime.BindQueryParameter("form", true, false, "collection_method", ctx.QueryParams(), &params.CollectionMethod)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter collection_method: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInvoices(ctx, params)
	return err
}

// PostInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) PostInvoice(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostInvoiceParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-CSRF-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-CSRF-Token")]; found {
		var XCSRFToken CsrfToken
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-CSRF-Token, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-CSRF-Token", valueList[0], &XCSRFToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-CSRF-Token: %s", err))
		}

		params.XCSRFToken = XCSRFToken
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-CSRF-Token is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInvoice(ctx, params)
	return err
}

// PostVerifyEmail converts echo context to params.
func (w *ServerInterfaceWrapper) PostVerifyEmail(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostVerifyEmailParams
	// ------------- Optional query parameter "redirect" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect", ctx.QueryParams(), &params.Redirect)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter redirect: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVerifyEmail(ctx, params)
	return err
}

// GetVerifyEmailConfirm converts echo context to params.
func (w *ServerInterfaceWrapper) GetVerifyEmailConfirm(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVerifyEmailConfirmParams
	// ------------- Required query parameter "token" -------------

	err = runtime.BindQueryParameter("form", true, true, "token", ctx.QueryParams(), &params.Token)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter token: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVerifyEmailConfirm(ctx, params)
	return err
}

// PostVerifyEmailConfirm converts echo context to params.
func (w *ServerInterfaceWrapper) PostVerifyEmailConfirm(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVerifyEmailConfirm(ctx)
	return err
}

// PostWebhookInvoicePaid converts echo context to params.
func (w *ServerInterfaceWrapper) PostWebhookInvoicePaid(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostWebhookInvoicePaidParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Stripe-Signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Stripe-Signature")]; found {
		var StripeSignature string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Stripe-Signature, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Stripe-Signature", valueList[0], &StripeSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Stripe-Signature: %s", err))
		}

		params.StripeSignature = StripeSignature
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Stripe-Signature is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostWebhookInvoicePaid(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/admin", wrapper.GetAdmins)
	router.GET(baseURL+"/checkout/sessions", wrapper.GetCheckoutSessions)
	router.GET(baseURL+"/csrf", wrapper.GetCsrf)
	router.GET(baseURL+"/customers", wrapper.GetCustomer)
	router.PATCH(baseURL+"/customers", wrapper.PatchCustomer)
	router.POST(baseURL+"/customers", wrapper.PostCustomer)
	router.GET(baseURL+"/invoices", wrapper.GetInvoices)
	router.POST(baseURL+"/invoices", wrapper.PostInvoice)
	router.POST(baseURL+"/verify-email", wrapper.PostVerifyEmail)
	router.GET(baseURL+"/verify-email/confirm", wrapper.GetVerifyEmailConfirm)
	router.POST(baseURL+"/verify-email/confirm", wrapper.PostVerifyEmailConfirm)
	router.POST(baseURL+"/webhook/invoice-paid", wrapper.PostWebhookInvoicePaid)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xba1fbRvr/Kjr690X7XxsDITd6ck4Tmja0NGGh3fYscc1YGmMllsYZjbikyzlIzoUc",
	"yLZJE1Ka9jR0c2FDC02zm6UhGz7MYAPfYs+MJFuyRsZckua0fZNgaS7P88zvuY8+kxWkF5EBDWLKnZ/J",
	"RYCBDgnE/FeXiXMforPQYD9UaCpYKxINGXKn/DaysgWYNK2srhGpq7/vHYmwkXTCGUwpJs4NStR+Tu3v",
	"qL0kDfae6v9QSg1DrOXGklAHWiGlICOnYZ0Nm16ffboxN03tW9T+ThrMZE4gkySVPFTOakbGXUxB6KwG",
	"JWovlifuUuc6tb+l9iLf4vnmhE2dKTrhnDbkhKwx8vIQqBDLCdkAOpQ75U+SjMSky0xCxvCcpWGoyp0E",
	"WzAhm0oe6oBxqWtGDzSGSF7ubDuQkMlYkU03CdaMIXl8PCF3WSZBOsTdalQo/jup+22fkHMWxGM1OhRv",
	"REZT5eC2cBToxYI3InMS/nVEPUl6jp/6xBo+JovIOG6omjF0DOYQhlFCKtOXy4tfU/smdaaZTLvfZpKj",
	"zkNamqHOMnUeUGeJlibXVu6Vr1wVvqLO9fLnM+Xnt2I4gZyATNalIMhLlNgeTddIlEp3/bWVJ5WbP8Xs",
	"UuAzg6urMAesApE721oTsg5GNd3S2Q/2SzO8X1WJaQaBQxBzKvoJwEQzho7mCMS7ktnm7M5kZnoUZAAn",
	"obHQ+q1slTwR2ILv4wFnBkbFg860ss2A7i9cgY8z/e2DqoahIjjVyt1vNuaflZ9PU3th0/7P+oMVas9S",
	"Z2r99nJ56TktXaPOLzHEYn/RIJWvYZiTO+X/S9UsVcp9a6b6YAEQbRj61PQCkpfHGakYmkVkmJDbsWNA",
	"7YPnLGgKyD0GVAl7L8cT8jsIZzVVFZm82qvxhNxtEIgNUOiHeBji4xgjAaT8QZLJR0mQDxtPyCcReQdZ",
	"huBUTyIi5fir8YT8kQEskkdYOw8FQ0NvGc+eVNjIo6quCVhYX5xb/+LSxsRFai9WShfLdx7JCbmIURFi",
	"ormy0gQ7EQz+7EKsBhmCQa8QJDXbOsAWS1fHoOwZdrYBG9rAgsYTyN1HdCZHZYjCM9AwxjAyofGW97BF",
	"QXqU5oSQ57At35599gEdOVz2NLjYe4xEqY/RKFqFYHAus+sDiYj/XUi6mHNFFumHpqkhw+zz1CW6Fbdy",
	"j2npn9S5S0uPK4+eVpYnaelrWnpGneX1G48q395jXvnivc3L19aWJzbuP4gcmQoIV2WNQN0NM0KvgY4s",
	"g2RMK0sQAYKzLV/5ufzsJi2trM//ffPyNWZmv1jgvv8htS9UbixVrtyk9oXNy9c2564GhdJ2+PChhJxD",
	"WAfE9QYHOuSoc0j4JMTs32CH9rYmd1AwBESkxmv//aYy+UXl1r3KrCO9/pGhjUqVWWdz5ss3QpwcOHj4",
	"QGtre9v+5nYLaFgjA1rVxDgt8HAieUCJaIOZIdAkmbb2fR37Dxw8dLhVhOMiGNOhQTKMQENgg6n9JbUX",
	"pchmzIPMfL858Y+1la+ofY06Vzzf3Osu2O2uFySoqGX2fUBGjo30nFW7R05YB7XR9kNgHznXC4SUYaRa",
	"ChEqWa/7rp5lNiVz8uMz5qGz72ff+1i3LEW0skkAscwmJMojiV9o6RLXqFXXO0KDxTEDPDovQOJajSI3",
	"qwkZFaHB7GqNJv6kKd33HgCMwRj7nQdmRhfHkD/MMdJ8Taf2NLUdFmfbU7WtsggVIDDEe3Ubw0hToMgv",
	"8hcNjHxzFkO1RHR/M7H+b2f96wvUXvAV91JUcVu3YxeKQASQqllgFtFe3eUemDk2gx1cg40WpzYXvtr+",
	"Frs2PodaD3R0dBw4+FKNjw+TOgXUjEzbB+RE9nhNxQsdp86f7/1geOfGZ2NhqvLIqdxe/i3anBpzsYZG",
	"xSBHfNvChMZzBctQUKEAFaJlC8wGDSM3oqtR5s97xUxPLzKJD6/Y0L8a4rlaQEsPWRrnzHMpTW438Nxe",
	"DLiTWK9xrA09Ovi26RiZeCoVKxJf5ZqTSLCasUUAvXMtaMx1uKASWHRLCcQFvL4IuM1kDhpD0yqQaKLk",
	"jsu8eMtlYQHsTiCTQFXyqJC8sdJHfT2hLfOEFM3OVMob18JWL/JEKNXS0rJ1AldjMkxPnHgDJYIut8IX",
	"wBpQVY2RDwq9AVHmQMGEiTr23HUkDmrJqxVW8/T6oyB+jTJQvdvXvhVv7qwmGNkDDuIoj7EpmqkQyVfo",
	"qsf1H+hg1Oeyff9+di6EQMzmfTrw6VunT5vpP701oHWnB8z+9IDSlR4gH6ZPn24ZAEf5T/bnmffSA8Xe",
	"9GtNWpWmhFRTqJ1KidfHJL9006ywDCafgnYeqlWRRVQJB8pVOygoiS1tdVGReIQrRWgfTKUGJWo/KD+Y",
	"Yvmsc8VNaanzPS3doqWH5UsXqb1YVzqraXdKh3oWYjOvFeUQDlKv/23g01S65f/feE0kjn5uBY4PewGR",
	"+Lzc0niY3nehAbGmSO4CEmQrMNtTQECVI1JggtOMHIrJgjRDOtrbzaZphLMTfjoMsemObm1pa2lldLPo",
	"BBQ1uVPexx9xnvMcHCngl7yGIGeKMQL84qn8LiS8JmbKdbXB9tZW7spQNTwExWJBU/jU1BkT8TVr5chq",
	"RtIIRm75LRLzMHmE5XDqfTaqo3Vf3IpVWlOh8uN+l+rGM0Q1Sl4ntHQd4LG6eqBbuwmWsAkYMhneXW7S",
	"bGpK8dLXlOlVjhpJvL7KxM+r1mAaEDNQG5IKNFvGE1uOrquYNzHDbUw0s3Sod9DEhFB/ho2vi3CCyUR8",
	"9T6cu9TX7yOWe2e1hphOBcskQt2CZkoS9SSld6ltjZSsURnz1VO1HdRRRbpYx7GvlSbONVRE9j5yFB2i",
	"9oPUhfwM122i8sH9kCS7eAtW4MMaNmyd6353d9Zt0jJowaSSB8aQZgz5kRFzgtReohO2Vwysb/hKg8Ee",
	"7qDkEidReyHYCqbOY1q6wWRq36L2/XBnWNT5EtB+hP2T5NFhchgULPimxJz3kdSbUj9ULAzflPqBDvs1",
	"Ao/0gFFBCDUePnreHaelSX7US7T0eP3GfEQ+QXtrkbx/sJ4BDJrZsPQ9O1yTl9d0X1ud27zzzK1MSUWM",
	"RsckYJG8RO3p8urFjfu2q7V1OPErMrs01HEZrMjU+Invtiybn3QLO9Peu/jlXqRVqhW14k1QEwYl0LLk",
	"U9q2nhLuB+7E1HW4JqHxjGrvcu9sY63rJ7J4vkDTPCUmSn4PlYBOOHV2hTpOefXi5p3JiH70sr13riHV",
	"uzQu/PjZHkPq2J4hT1TzGo82w/8A+5769SB2K7f/VZn5KRa7yCS/FnQD0PgDuc0ht92F4Qvfrcvrzfze",
	"lMUtMYuVhYU+XumxYYLZ7Y/5I7HcutWzzTxvex2hLSO2QINtsdbPnPml8vhm3F1JbyNkZHRI8kgVp6N5",
	"gIdgBlgE6YBoCigU2BomNNSMB6GXnZj6fe9XLwmtHkLT+abPyyvgwHxSXk3/VddZE7qvthezY3zN4/fk",
	"W6qXSgSupYZi5lmC99D53RIP11HIBfob24ad6LLsiwSgoGE1Hu5cEGzBKCjbXxwV8cA8qiiwuHNk7hFk",
	"eJuNluaYlywt8KbLFVr6gblOe3H9+6cbD68G3l7fnLDXVufEhRrRtw2NIpdonzQKsLq7u3X02AveJUhn",
	"mjpTtLRES4+5r79LS3eC1aa4ust2voUQdVO3dqEEjpJUnuiFMIYi5TKBlwxVH7uAkofJLmQQjAQNQFqa",
	"4XXV+9R5Qp0La8s/rj+ZpfbC2uq35R+/ovZNat92+2oxRUADJU3ifsYQLeW9PNO5V5VmHyI+YmpQCMDa",
	"v1vjXN+Ym1+/+zQK60RzhrEG3+Ys22hyZGQkmUNYT1q4AA0Fqe7NtB0ZmbpLBk1YvH2ug6r7mAJC6RTJ",
	"8+z41QBeQu5BrsRiP7FYnF57emnLDy129SVFYluVfy8UHJSoPS9tsy0QM96r/9tLayv3OKuLUnwD4eX0",
	"CDwuj3j/u52CWo/gBCHFU0ZhbBvdgt+UiXGuV55Mbvy84kqXln6kzk9uz4vlFxyzYhc6ArN5hM76iX/S",
	"v3Qbb4U+dmd40V0v8G4pNXCi3r0Fak+7ztyF38bDqxvzz6pXkYVfELozk/3akAGIxVU23nMKXeXeh33B",
	"axxNxXrijp9Py68ai3lnyRTev9TWwhAgcezM8t6p+4HdLWpfK38+Q52pAI686QxK49Wn9bwysHmXS7xT",
	"5fATNM79OlVocOC+ctyFv9D4ah0gMtxnNjTcZyG+j++38cNU1XWEo9P5/Y06vt0LKunx/wUAAP//K9no",
	"qwE8AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
