// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CsrfTokenHeaderScopes      = "CsrfTokenHeader.Scopes"
	EmailVerifiedSessionScopes = "EmailVerifiedSession.Scopes"
	NewShowcaseAuthScopes      = "NewShowcaseAuth.Scopes"
)

// Defines values for GetCheckoutSessionsResponseDataStatus.
const (
	GetCheckoutSessionsResponseDataStatusComplete GetCheckoutSessionsResponseDataStatus = "complete"
	GetCheckoutSessionsResponseDataStatusExpired  GetCheckoutSessionsResponseDataStatus = "expired"
	GetCheckoutSessionsResponseDataStatusOpen     GetCheckoutSessionsResponseDataStatus = "open"
)

// Defines values for InvoiceStatus.
const (
	InvoiceStatusDraft         InvoiceStatus = "draft"
	InvoiceStatusOpen          InvoiceStatus = "open"
	InvoiceStatusPaid          InvoiceStatus = "paid"
	InvoiceStatusUncollectible InvoiceStatus = "uncollectible"
	InvoiceStatusVoid          InvoiceStatus = "void"
)

// Defines values for GetCheckoutSessionsParamsStatus.
const (
	Complete GetCheckoutSessionsParamsStatus = "complete"
	Expired  GetCheckoutSessionsParamsStatus = "expired"
	Open     GetCheckoutSessionsParamsStatus = "open"
)

// Defines values for GetInvoicesParamsCollectionMethod.
const (
	ChargeAutomatically GetInvoicesParamsCollectionMethod = "charge_automatically"
	SendInvoice         GetInvoicesParamsCollectionMethod = "send_invoice"
)

// Admin 管理者の情報
type Admin struct {
	// Id traQ ID
	Id string `json:"id"`
}

// Customer Customer の情報
type Customer struct {
	// Email Email
	Email *string `json:"email,omitempty"`

	// Id Customer ID
	Id *string `json:"id,omitempty"`

	// Name Name
	Name *string `json:"name,omitempty"`

	// TraqId traQ ID
	TraqId *string `json:"traq_id,omitempty"`
}

// GetCheckoutSessionsResponse オンライン決済ページ由来の入金一覧
type GetCheckoutSessionsResponse struct {
	Data *[]struct {
		// AmountSubtotal 割引・税金を含まない支払い金額
		AmountSubtotal *int64 `json:"amount_subtotal,omitempty"`

		// AmountTotal 支払い金額
		AmountTotal *int64 `json:"amount_total,omitempty"`

		// Created 作成日時 (Unix 時間)
		Created *int64 `json:"created,omitempty"`

		// Customer Customer の情報
		Customer *Customer `json:"customer,omitempty"`

		// Id Checkout Session ID
		Id *string `json:"id,omitempty"`

		// PaymentIntent この Checkout Session に関連付けられた PaymentIntent
		PaymentIntent *string `json:"payment_intent,omitempty"`

		// ProductId Product ID
		ProductId *string `json:"product_id,omitempty"`

		// Status Checkout Session のステータス
		Status *GetCheckoutSessionsResponseDataStatus `json:"status,omitempty"`
	} `json:"data,omitempty"`

	// HasMore 次のページがあるか
	HasMore *bool `json:"has_more,omitempty"`
}

// GetCheckoutSessionsResponseDataStatus Checkout Session のステータス
type GetCheckoutSessionsResponseDataStatus string

// GetInvoicesResponse Invoice の情報
type GetInvoicesResponse struct {
	Data *[]struct {
		// AmountDue 最終的に支払う金額
		AmountDue *int64 `json:"amount_due,omitempty"`

		// AmountPaid 支払い済み金額
		AmountPaid *int64 `json:"amount_paid,omitempty"`

		// AmountRemaining 支払い残高
		AmountRemaining *int64 `json:"amount_remaining,omitempty"`

		// Created 作成日時 (Unix 時間)
		Created *int64 `json:"created,omitempty"`

		// Customer Customer の情報
		Customer *Customer `json:"customer,omitempty"`

		// Id Invoice ID
		Id *string `json:"id,omitempty"`

		// PaymentIntent この請求書に関連付けられた PaymentIntent
		PaymentIntent *string `json:"payment_intent,omitempty"`

		// ProductId Product ID
		ProductId *string `json:"product_id,omitempty"`

		// Status 請求書ステータス
		Status *InvoiceStatus `json:"status,omitempty"`
	} `json:"data,omitempty"`

	// HasMore 次のページがあるか
	HasMore *bool `json:"has_more,omitempty"`
}

// InvoiceStatus 請求書ステータス
type InvoiceStatus string

// PatchCustomerRequest Customer 更新リクエスト (すべてのフィールドはオプショナル)
type PatchCustomerRequest struct {
	// Email Email
	Email *string `json:"email,omitempty"`

	// Name Name
	Name *string `json:"name,omitempty"`

	// TraqId traQ ID
	TraqId *string `json:"traq_id,omitempty"`
}

// PostCustomerRequest Customer 作成リクエスト
type PostCustomerRequest struct {
	// Email Email
	Email string `json:"email"`

	// Name Name
	Name string `json:"name"`

	// TraqId traQ ID
	TraqId *string `json:"traq_id,omitempty"`
}

// PostInvoiceRequest Invoice 作成リクエスト
type PostInvoiceRequest struct {
	// CustomerId Customer ID
	CustomerId string `json:"customer_id"`

	// ProductId Product ID
	ProductId string `json:"product_id"`
}

// PostInvoiceResponse Invoice creation result
type PostInvoiceResponse struct {
	// InvoiceId Invoice ID
	InvoiceId string `json:"invoice_id"`

	// PaymentUrl Hosted invoice payment URL
	PaymentUrl string `json:"payment_url"`
}

// PostVerifyEmailConfirmRequest Verify email confirm request
type PostVerifyEmailConfirmRequest struct {
	Token string `json:"token"`
}

// PostVerifyEmailRequest Verify email request
type PostVerifyEmailRequest struct {
	// Email isct email
	Email openapi_types.Email `json:"email"`
}

// PostVerifyEmailResponse Verify email start response
type PostVerifyEmailResponse struct {
	// Email normalized email
	Email string `json:"email"`

	// Redirect `//` で始まらないアプリ内の相対パス
	Redirect RelativeRedirectPath `json:"redirect"`
}

// RelativeRedirectPath `//` で始まらないアプリ内の相対パス
type RelativeRedirectPath = string

// StripeEvent Generic Stripe event payload
type StripeEvent map[string]interface{}

// CustomerId defines model for CustomerId.
type CustomerId = string

// EndingBefore defines model for EndingBefore.
type EndingBefore = string

// Limit defines model for Limit.
type Limit = int

// StartingAfter defines model for StartingAfter.
type StartingAfter = string

// SubscriptionId defines model for SubscriptionId.
type SubscriptionId = string

// VerifyEmailRedirect `//` で始まらないアプリ内の相対パス
type VerifyEmailRedirect = RelativeRedirectPath

// GetCheckoutSessionsParams defines parameters for GetCheckoutSessions.
type GetCheckoutSessionsParams struct {
	// CustomerId Customer ID
	CustomerId *CustomerId `form:"customer_id,omitempty" json:"customer_id,omitempty"`

	// SubscriptionId Subscription ID
	SubscriptionId *SubscriptionId `form:"subscription_id,omitempty" json:"subscription_id,omitempty"`

	// Limit 取得件数
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter 指定された ID のオブジェクト以降のオブジェクトを取得
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore 指定された ID のオブジェクト以前のオブジェクトを取得
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`

	// PaymentIntentId PaymentIntent ID
	PaymentIntentId *string `form:"payment_intent_id,omitempty" json:"payment_intent_id,omitempty"`

	// Status Checkout Session のステータス
	Status *GetCheckoutSessionsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetCheckoutSessionsParamsStatus defines parameters for GetCheckoutSessions.
type GetCheckoutSessionsParamsStatus string

// GetCustomerParams defines parameters for GetCustomer.
type GetCustomerParams struct {
	// CustomerId Customer ID
	CustomerId *CustomerId `form:"customer_id,omitempty" json:"customer_id,omitempty"`

	// TraqId traQ ID
	TraqId *string `form:"traq_id,omitempty" json:"traq_id,omitempty"`

	// Email Email
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}

// GetInvoicesParams defines parameters for GetInvoices.
type GetInvoicesParams struct {
	// CustomerId Customer ID
	CustomerId *CustomerId `form:"customer_id,omitempty" json:"customer_id,omitempty"`

	// SubscriptionId Subscription ID
	SubscriptionId *SubscriptionId `form:"subscription_id,omitempty" json:"subscription_id,omitempty"`

	// Limit 取得件数
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// StartingAfter 指定された ID のオブジェクト以降のオブジェクトを取得
	StartingAfter *StartingAfter `form:"starting_after,omitempty" json:"starting_after,omitempty"`

	// EndingBefore 指定された ID のオブジェクト以前のオブジェクトを取得
	EndingBefore *EndingBefore `form:"ending_before,omitempty" json:"ending_before,omitempty"`

	// Status 請求書ステータス
	Status *InvoiceStatus `form:"status,omitempty" json:"status,omitempty"`

	// CollectionMethod 請求書の支払い方法
	CollectionMethod *GetInvoicesParamsCollectionMethod `form:"collection_method,omitempty" json:"collection_method,omitempty"`
}

// GetInvoicesParamsCollectionMethod defines parameters for GetInvoices.
type GetInvoicesParamsCollectionMethod string

// PostVerifyEmailParams defines parameters for PostVerifyEmail.
type PostVerifyEmailParams struct {
	// Redirect 検証後に遷移する相対パス
	Redirect *VerifyEmailRedirect `form:"redirect,omitempty" json:"redirect,omitempty"`
}

// GetVerifyEmailConfirmParams defines parameters for GetVerifyEmailConfirm.
type GetVerifyEmailConfirmParams struct {
	// Token 確認メールに含まれるワンタイムトークン
	Token string `form:"token" json:"token"`
}

// PostWebhookInvoicePaidParams defines parameters for PostWebhookInvoicePaid.
type PostWebhookInvoicePaidParams struct {
	// StripeSignature Stripe が送信する認証情報
	StripeSignature string `json:"Stripe-Signature"`
}

// PatchCustomerJSONRequestBody defines body for PatchCustomer for application/json ContentType.
type PatchCustomerJSONRequestBody = PatchCustomerRequest

// PostCustomerJSONRequestBody defines body for PostCustomer for application/json ContentType.
type PostCustomerJSONRequestBody = PostCustomerRequest

// PostInvoiceJSONRequestBody defines body for PostInvoice for application/json ContentType.
type PostInvoiceJSONRequestBody = PostInvoiceRequest

// PostVerifyEmailJSONRequestBody defines body for PostVerifyEmail for application/json ContentType.
type PostVerifyEmailJSONRequestBody = PostVerifyEmailRequest

// PostVerifyEmailConfirmFormdataRequestBody defines body for PostVerifyEmailConfirm for application/x-www-form-urlencoded ContentType.
type PostVerifyEmailConfirmFormdataRequestBody = PostVerifyEmailConfirmRequest

// PostWebhookInvoicePaidJSONRequestBody defines body for PostWebhookInvoicePaid for application/json ContentType.
type PostWebhookInvoicePaidJSONRequestBody = StripeEvent

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 管理者の一覧を取得
	// (GET /admin)
	GetAdmins(ctx echo.Context) error
	// オンライン決済ページ由来の入金一覧を取得
	// (GET /checkout/sessions)
	GetCheckoutSessions(ctx echo.Context, params GetCheckoutSessionsParams) error
	// CSRF トークン用 cookie を発行
	// (GET /csrf)
	GetCsrf(ctx echo.Context) error
	// Customer を取得
	// (GET /customers)
	GetCustomer(ctx echo.Context, params GetCustomerParams) error
	// Customer を更新
	// (PATCH /customers)
	PatchCustomer(ctx echo.Context) error
	// Customer を作成
	// (POST /customers)
	PostCustomer(ctx echo.Context) error
	// 請求書由来の入金一覧を取得
	// (GET /invoices)
	GetInvoices(ctx echo.Context, params GetInvoicesParams) error
	// Invoice を作成
	// (POST /invoices)
	PostInvoice(ctx echo.Context) error
	// isct メールアドレスの確認メールを送信
	// (POST /verify-email)
	PostVerifyEmail(ctx echo.Context, params PostVerifyEmailParams) error
	// メール確認トークンの確認ページを表示
	// (GET /verify-email/confirm)
	GetVerifyEmailConfirm(ctx echo.Context, params GetVerifyEmailConfirmParams) error
	// メール確認トークンを消費してログインを完了
	// (POST /verify-email/confirm)
	PostVerifyEmailConfirm(ctx echo.Context) error
	// Webhook の invoice.paid イベントを受け取る
	// (POST /webhook/invoice-paid)
	PostWebhookInvoicePaid(ctx echo.Context, params PostWebhookInvoicePaidParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAdmins converts echo context to params.
func (w *ServerInterfaceWrapper) GetAdmins(ctx echo.Context) error {
	var err error

	ctx.Set(EmailVerifiedSessionScopes, []string{})

	ctx.Set(NewShowcaseAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAdmins(ctx)
	return err
}

// GetCheckoutSessions converts echo context to params.
func (w *ServerInterfaceWrapper) GetCheckoutSessions(ctx echo.Context) error {
	var err error

	ctx.Set(EmailVerifiedSessionScopes, []string{})

	ctx.Set(NewShowcaseAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCheckoutSessionsParams
	// ------------- Optional query parameter "customer_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "customer_id", ctx.QueryParams(), &params.CustomerId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter customer_id: %s", err))
	}

	// ------------- Optional query parameter "subscription_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "subscription_id", ctx.QueryParams(), &params.SubscriptionId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter subscription_id: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", ctx.QueryParams(), &params.StartingAfter)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter starting_after: %s", err))
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", ctx.QueryParams(), &params.EndingBefore)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ending_before: %s", err))
	}

	// ------------- Optional query parameter "payment_intent_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "payment_intent_id", ctx.QueryParams(), &params.PaymentIntentId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter payment_intent_id: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCheckoutSessions(ctx, params)
	return err
}

// GetCsrf converts echo context to params.
func (w *ServerInterfaceWrapper) GetCsrf(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCsrf(ctx)
	return err
}

// GetCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) GetCustomer(ctx echo.Context) error {
	var err error

	ctx.Set(EmailVerifiedSessionScopes, []string{})

	ctx.Set(NewShowcaseAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomerParams
	// ------------- Optional query parameter "customer_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "customer_id", ctx.QueryParams(), &params.CustomerId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter customer_id: %s", err))
	}

	// ------------- Optional query parameter "traq_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "traq_id", ctx.QueryParams(), &params.TraqId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter traq_id: %s", err))
	}

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameter("form", true, false, "email", ctx.QueryParams(), &params.Email)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCustomer(ctx, params)
	return err
}

// PatchCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) PatchCustomer(ctx echo.Context) error {
	var err error

	ctx.Set(CsrfTokenHeaderScopes, []string{})

	ctx.Set(EmailVerifiedSessionScopes, []string{})

	ctx.Set(CsrfTokenHeaderScopes, []string{})

	ctx.Set(NewShowcaseAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchCustomer(ctx)
	return err
}

// PostCustomer converts echo context to params.
func (w *ServerInterfaceWrapper) PostCustomer(ctx echo.Context) error {
	var err error

	ctx.Set(CsrfTokenHeaderScopes, []string{})

	ctx.Set(EmailVerifiedSessionScopes, []string{})

	ctx.Set(CsrfTokenHeaderScopes, []string{})

	ctx.Set(NewShowcaseAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostCustomer(ctx)
	return err
}

// GetInvoices converts echo context to params.
func (w *ServerInterfaceWrapper) GetInvoices(ctx echo.Context) error {
	var err error

	ctx.Set(EmailVerifiedSessionScopes, []string{})

	ctx.Set(NewShowcaseAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInvoicesParams
	// ------------- Optional query parameter "customer_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "customer_id", ctx.QueryParams(), &params.CustomerId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter customer_id: %s", err))
	}

	// ------------- Optional query parameter "subscription_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "subscription_id", ctx.QueryParams(), &params.SubscriptionId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter subscription_id: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "starting_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "starting_after", ctx.QueryParams(), &params.StartingAfter)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter starting_after: %s", err))
	}

	// ------------- Optional query parameter "ending_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "ending_before", ctx.QueryParams(), &params.EndingBefore)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ending_before: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "collection_method" -------------

	err = runtime.BindQueryParameter("form", true, false, "collection_method", ctx.QueryParams(), &params.CollectionMethod)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter collection_method: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetInvoices(ctx, params)
	return err
}

// PostInvoice converts echo context to params.
func (w *ServerInterfaceWrapper) PostInvoice(ctx echo.Context) error {
	var err error

	ctx.Set(CsrfTokenHeaderScopes, []string{})

	ctx.Set(EmailVerifiedSessionScopes, []string{})

	ctx.Set(CsrfTokenHeaderScopes, []string{})

	ctx.Set(NewShowcaseAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostInvoice(ctx)
	return err
}

// PostVerifyEmail converts echo context to params.
func (w *ServerInterfaceWrapper) PostVerifyEmail(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostVerifyEmailParams
	// ------------- Optional query parameter "redirect" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect", ctx.QueryParams(), &params.Redirect)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter redirect: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVerifyEmail(ctx, params)
	return err
}

// GetVerifyEmailConfirm converts echo context to params.
func (w *ServerInterfaceWrapper) GetVerifyEmailConfirm(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetVerifyEmailConfirmParams
	// ------------- Required query parameter "token" -------------

	err = runtime.BindQueryParameter("form", true, true, "token", ctx.QueryParams(), &params.Token)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter token: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVerifyEmailConfirm(ctx, params)
	return err
}

// PostVerifyEmailConfirm converts echo context to params.
func (w *ServerInterfaceWrapper) PostVerifyEmailConfirm(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVerifyEmailConfirm(ctx)
	return err
}

// PostWebhookInvoicePaid converts echo context to params.
func (w *ServerInterfaceWrapper) PostWebhookInvoicePaid(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostWebhookInvoicePaidParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "Stripe-Signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Stripe-Signature")]; found {
		var StripeSignature string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for Stripe-Signature, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Stripe-Signature", valueList[0], &StripeSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter Stripe-Signature: %s", err))
		}

		params.StripeSignature = StripeSignature
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter Stripe-Signature is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostWebhookInvoicePaid(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/admin", wrapper.GetAdmins)
	router.GET(baseURL+"/checkout/sessions", wrapper.GetCheckoutSessions)
	router.GET(baseURL+"/csrf", wrapper.GetCsrf)
	router.GET(baseURL+"/customers", wrapper.GetCustomer)
	router.PATCH(baseURL+"/customers", wrapper.PatchCustomer)
	router.POST(baseURL+"/customers", wrapper.PostCustomer)
	router.GET(baseURL+"/invoices", wrapper.GetInvoices)
	router.POST(baseURL+"/invoices", wrapper.PostInvoice)
	router.POST(baseURL+"/verify-email", wrapper.PostVerifyEmail)
	router.GET(baseURL+"/verify-email/confirm", wrapper.GetVerifyEmailConfirm)
	router.POST(baseURL+"/verify-email/confirm", wrapper.PostVerifyEmailConfirm)
	router.POST(baseURL+"/webhook/invoice-paid", wrapper.PostWebhookInvoicePaid)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xb/VfUxvr/V3Ly7Q/t9+6ygPhGj+dUqVZaq1y33vZc3C5DMrDRTbJOJrzo5RyS+MYF",
	"22oFpdrTYn2hUEHrvRbFi3/MsLvwX9wzk2Q32UyWBaXttf1FSTIvzzzzeT7zvMyeEyVdLega1LAhtp8T",
	"CwABFWKI2FOHaWBdhahTpk8yNCSkFLCia2J75ZvQ+b6YEBX66owJ0bCYEDWgQrFdlLwWWUUWE6Ih5aAK",
	"6DhwCKiFvNciexT+fVA+io8cPPaZOXBATIh4uEC/GRgpWr84MpIQD2qyovUfgH06glFBShOXigvfEGuS",
	"2BPE+k7ofF8g1gKx54gzRewlYj8g9iJxLq8u3yuOXeF+Iva14pdTxZUbMSuBTIBsrytBcC1RYY8oqoKj",
	"Urrjry4/LU0+ipklz3oGR5dhHzDzWGxvaU6IKhhSVFOlD/RJ0bynisYUDcN+iJgUaQwQVrT+/X0YolfS",
	"2fr01nRmeBJkAROhvtLSZm9FPB7Ygt/jAWcEWsWDzjB7GwHd3yBS+oYPqkDJH4eygqDE2dXS3dtrsy+K",
	"KxPEml+3fik/WCbWNLHHy7eWiosrxLlK7GcxwiJ/0KCUbyHYJ7aL/5eqWmXK/WqkjsM8wMoA9KXpAjgn",
	"jlBRETQKumZAZrMHgHwcnjGhwRH3AJAF5H0cSYiHdNSryDLUoi2rn0YSYqeGIdJAPg3RAEQHEdI5kPIb",
	"CQZrJUDWbCQhHtXxId3UOLt6VMdCH/s0khBPaMDEOR0pZyGnaegrXbOnFdpyv6wqnCWUF2bKX11cG71A",
	"rIWSc6H4/WMxIRaQXoAIK66uFM5MGIG/uhCrQgYj0MUFCVWmgqjA3XSwTKWN3nuK7u1IosKTdRg0XkBI",
	"4RftyVAZkvAU1LRhpBtQe8972STpalTmBHfNYS7fHD/7gI5sLn0bHOxDKqJwnMrIGwUjcCb7yhsSUf8H",
	"EHfkoHRaN3EaGoaia8Zxz1yiUzGWe0KcH4l9lzhPSo+fl5YuE+cb4rwg9lL5+uPSt/eItVC8cG/90tXV",
	"pdG1+w8iWyYDzExZwVB1j9TQZ6DqpoazhtmLdQw4e1sc+7n4YpI4y+XZL9YvXaU0+9U8sVaINUes86Xr",
	"i6WxSWKdX790dX3mSlApLXv37kmIfTpSAXZPg11tYvRwSPgixMxfZ4bWlgZnkBAEmGfGq/+5Xbr8VenG",
	"vdK0Lbx9QlOGhNK0vT719TuhlezavXdXc3Nry87GZgtYWD0CrVhinBV4OBE8oESswchiaOBsS+uOtp27",
	"du/Z28zDcQEMq1DDWSqgxuFgYn1NrAUhMhk9QaburI/+sLp8k1hXiT3mnc1d7oCd7nhBgQpKdsfHePDA",
	"4JHTcufgYXO3MtS6B+zAZ7oAVzKky6aEuUbW5X6rXTLtkj366Sljz+mPej/8VDVNiTeygQE2jQY0yjyJ",
	"Z8S5yCzqpXs6Qo36Md3ME81D7LJGgdFqQtQLUKO8WpWJvWnI9r0XACEwTJ9zwMiqfB/ypxkqmm/pxJog",
	"lk3scWKNV6fq1fU8BFosz3RqA7oiwTr84rWoQ/iNsYds8tZwe7T8b7v8zXlizftGfDFqxM2b4YgC4IGl",
	"QhGUHa2XrzgHooecRjexzkQL4+vzNzc/xSsT0Z7mXW1tbbt2/6pE5MOkxhgVLdvyMT7ce7Bq7vm2Y2fP",
	"dn08sHUiWpsfLz22S7eW3gz+qad2T61pt/FvzhhhcSITVDcmljBlBPqwz5F0w1nMY2qSns9DCSu9ecql",
	"A7rrmVa16veL6LELYCnnozM2iqh4i6Vb/ypNPSLOHI0I7Vkm6GXhbRoCWc+IdZ8paJLYP1DhnXnijBFr",
	"kflYN4j9C3EeEOefxJl/Z7Nu7+Y80K14mg0cLl26gRtXlcs3Nar6X1h3MMKBnhxs2kyMTjxYx6rEJ7fG",
	"NBLMIW0Qtmydb+qvOpzGCgy6oQY2cgPY6UTdIgQNM4+j4anbLrv9Z4SJOLA7rBsYyoInheC1FU4cPxKa",
	"ModxwWhPpbx2TXT0Ags/U01NTRuHzdVFhuWJU28gMdOha30KUgNYA7KsUPFBviugyj6QN2CiZnnuOAID",
	"tSC5I1WyI7VbgfXTbppEVbQjUOvHObF9R+tGa3N7NbCQ17CCOMljOEUxJCz4Bl3xbfwXKhjyV9m6cyfd",
	"F4whov0+7/78vZMnjcxf3utWOjPdRjrTLXVkuvEnmZMnm7rBfvZI/zz1Yaa70JV5q0FWaUhJVYPaqpZY",
	"VlLwE2aNKkuj+skrZ6FcUVnElFAgSbiFNB6faSuD8tTDHSkie08q1SMQ60HxwTixVqhbxxIJxL5Dj2Fn",
	"rnjxArEWahKWVetOqVDthcjIKQUxhIPU2//o/jyVafr/d97iqSPNWODggOd68vcLIzOyXR9ADSJFEtwB",
	"BEhHoNyT14EsRrRAnT8omUjBw2mqYHcbOwzU9wm1vcMQyLzU2/u62ZuHScPsVRUsdKSPHyourpQfTpWv",
	"zxLnJnEc4oxSp2XUFnpSkoH6qApXiPUdsRaFnq5j6U+E1ADDVZJtVcrjD9psojz9fG1mglg3qPfck81S",
	"Hk1KNBRWtKw7mKTrpxUWBxZH7xL7GrG+pc4SnWJlfdSifuSofVLzU8c5dxmV3PFnSSpyki2xqhNQUD6C",
	"zG1l5sJwr0DZi705AYAz4zlmFAtjxPmJHsLWQmlstHR7rDT7Y/nO87W5K8SaJ/ZlYv1ArPvlO8/L8+Ne",
	"3cAeX10aLU27IeccsZep3jy/7kkHW6G/AMl/8hZQoxSmw+yAJ3DW8CTmrOwoHEzn9EEJGHC/yYN7oAHD",
	"90NiPyT2L+Vrj4p3nNWlcWI9WLs0VxyfXF2+ubr0RXUpL2fWv3/hBrTEuc/c7afEebE2d2Vt9kX8RhzS",
	"0SBAMpSTJwz2pUZkilBF69NjkiOKJuzv6qTdFMzsLfx2ACJ378TmppamZqoB6uyDgiK2izvYK2aUOQb7",
	"FPAz4f2QWR21NODXVMQPIGapckOsKRm0NjczX0uvRIqgUMgrEuuaOmW44KlWKSrJiXo852blIzEV1UdY",
	"D8c+oq3amnfEjViRNRWqSux0pa7fg1e6CJKG2N59LsZcujMjiXNRwHVnRjIJ0TBVFaDhmjKDmxIOVsYw",
	"6DcoobvayNCpU5KXFUt5ODfq7Vht8prtd7VG281XQLVJKlDDpevZoHVNIa6BHm69s5GhQyXJBjqEyr60",
	"fY0LH8xLxBcFw2mQ2rJgxDXZWgozpgBKA/tQEbKRTGetSJlXtNZ6RlqvOvLmmeoWyjs8W67RmG/VBuqr",
	"a8j0e2Qr23hVUaFD95Nt7oHDGqchTnqnatTJq+tl2Nd8l2Ta9SwoNGFSygGtX9H6/dCBeonEWiSjllej",
	"qPVShJ6g49EjuMIJ1EEI+C/EfkKc61Sn1AO6H3ZneAV5juz76D9JFj4lB0DehO8K1Lvdl3pXSFM4wHeF",
	"NFBhWsFw3xEwxIkxRmqgEwICXYRAnMts4xeJ86R8fTairSB7Uzh52+zRaX3S9hO8r0jWcWkaHt342Z1N",
	"sZufWeJeevG+xQ+3ncxUzZHH01ADpBK4DcG6tGzcJXzVYCt01+aadf0elWsRvx9+rF5I4LGevyEZljfC",
	"Ui4K/VD+WHRDWmjgA7o8/NqAwc1Rj0TvwfwJxtdx9nKx4eb9Y7GhGxxWDKbLtwsZnIz8bw6MVneXt322",
	"Dq/S+UfDoltG4GORntdeernuce0X7v+MrRooPjYY6myqEBs/vbVQvQMw9az0ZDLurrFX8tS1rApxTpf5",
	"cVcOoH6YBSbWVYAVCeTzdAwDanLWA8pvEIFF7o28eZFXZUMbDrI6/e2oe6L4rbbvQKkpZ3LPk5btmTEe",
	"DX8ksq/cmeJwfRUklOqDCXl2dSoWNoGi0qY5n3cv3GWI7QEgp0o4Ei4XYWTCKChbt0+KeGDulyRY2Doy",
	"XxdbhbiHVTrjah1eiaP69dr6qLX6coYf/PNKPvUci2ipOgq3mkvrNfJY897tX1akIM4icZ6wo/gucb4P",
	"ZjDisgJeiSiMluDZuEFBe+OzD8MhnMphNR9GVCQhwznSQvmtDiDlYLJD1zDS87xq1RTL3N0n9lNin19d",
	"elh+Ok2s+dWX3xYf3iTWJLFuuaXNmDSTpicN7P5+J5os+vWIdFswXgGMj58qMAIg9++q2dfWZmbLd59H",
	"QZ5ojDSrYG6M9YaSg4ODyT4dqUkT5aEm6bJ7KXNLBFRz66MBNtzhHl41vymCUDiGcywc/X3AMCEe0V2N",
	"xf7SaGFi9fnFDX9v9Eo/KEpsKtPML932CMSaFTaZlY5p76WfrcXV5Xts5QtCfP7610lR8xe9z/vfzVtX",
	"M9aHMS4c0/LDm8hdv8F0ZF8rPb289vOyq3pWoH/k1mNoGMDwzT98B2FvTtdP+xF90r+bHs9Yn7o9PC+x",
	"C3hXzOocv96lE2JNuG6Ai033DkDlxj73JoDbM5lW+jWATQTrnrncQ/b1u4/BOzgN+Yz8apQvy+/Ip/N2",
	"lnKDfz+xieJBYEiaZlU+9xeqN4h1tfjlFLHHA6jyulNg1Ya5katDdOJ6sS+3Q0xA7M1fq2PaxLvw4aGJ",
	"deIUo/3EV6hx4OcEcbdEQ+39qCna3FdrqLmvrPjauF8aD0tVUyWNdmd3ImrW7V4ayYz8NwAA//9ARtGQ",
	"mD4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
