name: Run Spectral on Pull Requests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - run: npm install

      # Run Spectral
      - run: npx spectral lint openapi.yaml --ruleset @stoplight/spectral/rulesets/oas
